version: '3'
services:
  database:
    image: mongo
    container_name: "mongodb"
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: xchangerepo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_DATA_DIR: '/data/db'
    volumes:
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./db/data/:/data/db/
  mongo-express:
    image: mongo-express
    container_name: "mongoexpress"
    depends_on:
      - 'database'
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'false'
      ME_CONFIG_MONGODB_AUTH_DATABASE: xchangerepo
      ME_CONFIG_MONGODB_AUTH_USERNAME: root
      ME_CONFIG_MONGODB_AUTH_PASSWORD: password
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: password
  apirequest:
    image: 'node:10-alpine'
    container_name: "apirequest"
    depends_on:
      - 'database'
    volumes:
      - './api:/home/node/app'
    working_dir: '/home/node/app'
    ports:
      - '1234:1234'
    command:
      - 'npm install && npx nodemon ./api_request.js'
  webreact:
    image: 'node:10-alpine'
    container_name: "webreact"
    depends_on:
      - 'database'
    volumes:
      - './client:/home/node/app/client'
      - './server:/home/node/app/server'
    working_dir: '/home/node/app'
    ports:
      - '8080:8080'
    command:
      - 'cd client && npm install && npm start'
      - 'cd ../server && npm install && npm start'
