version: '2'
services:
  web:
    image: 'node:10-alpine'
    depends_on:
      - 'mongo'
    ports:
      - '3000:3000'
      - '8080:8080'
    volumes:
      - './:/home/node/app/'
      - './API:/home/node/app/API'
      - './WEB:/home/node/app/WEB'
    working_dir: '/home/node/app'
    command:
      - 'npm install'
      - 'npm start'
  database:
    image: 'mongo'
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - './BDD:/usr/local/BDD'
    working_dir: '/usr/local/SampleCollections'